spring.datasource.url=jdbc:postgresql://localhost:5432/prod
spring.datasource.username=app_user
spring.datasource.password=12341234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
